;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-word-begin
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-end
        evil-insert
        evil-insert-line
        evil-normal-state
        evil-scroll-line-up
        evil-undo
        evil-visual-char
        evil-window-up
        evil-yank
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        mark-sexp
        mark-word
        move-text-down
        paredit-delete-char
        shell-command
        toggle-input-method
        ))

(setq mc/cmds-to-run-once
      '(
        compile
        electric-pair-delete-pair
        enlarge-window
        evil-backward-char
        evil-delete
        evil-delete-backward-char-and-join
        evil-previous-line
        evil-search-next
        evil-window-down
        evil-window-next
        evil-window-up
        pixel-scroll-precision
        previous-error
        smex
        text-scale-adjust
        ))
